# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[main.params]
icon = "home"
newtab = false

[[main]]
identifier = "posts"
name = "Posts"
url = "/posts"
weight = 2
[main.params]
icon = "archives"
newtab = false

[[main]]
identifier = "categories"
name = "Categories"
url = "/categories"
weight = 3
[main.params]
icon = "categories"
newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/pandas2025"

[social.params]
icon = "brand-github"


